<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Autofac" Version="9.0.0" />
    <PackageReference Include="Azure.Storage.Files.Shares" Version="12.24.0" />
    <PackageReference Include="ESFA.DC.FileService" Version="0.2.0" />
    <PackageReference Include="ESFA.DC.ILR.FundingService.FM36.FundingOutput.Model" Version="0.1.446" />
    <PackageReference Include="ESFA.DC.JobContext.Interface" Version="0.4.1" />
    <PackageReference Include="ESFA.DC.JobContextManager" Version="0.4.1" />
    <PackageReference Include="ESFA.DC.Queueing" Version="0.1.18-beta0001" />
    <PackageReference Include="ESFA.DC.Serialization.Json" Version="0.2.0" />
    <PackageReference Include="Microsoft.Azure.ServiceBus" Version="5.2.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="NServiceBus" Version="8.1.1" />
    <PackageReference Include="NServiceBus.Newtonsoft.Json" Version="3.0.0" />
    <PackageReference Include="NServiceBus.Transport.AzureServiceBus" Version="3.2.1" />
    <PackageReference Include="SFA.DAS.Payments.EarningEvents.Messages.External" Version="2.0.7-prerelease-106" />
    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Spike.FM36Tool.Core\Spike.FM36Tool.Core.csproj" />
  </ItemGroup>
</Project>